// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// Code generated by k8s-infra-gen. DO NOT EDIT.
package v20150101

// +kubebuilder:validation:Enum={"Australia East","Australia Southeast","Brazil South","Canada Central","Canada East","Central India","Central US","East Asia","East US","East US 2","global","Japan East","Japan West","Korea Central","Korea South","North Central US","North Europe","South Central US","South India","Southeast Asia","UK South","UK West","West Central US","West Europe","West India","West US","West US 2"}
type ResourceLocationsEnum1 string

const (
	ResourceLocationsEnum1AustraliaEast      = ResourceLocationsEnum1("Australia East")
	ResourceLocationsEnum1AustraliaSoutheast = ResourceLocationsEnum1("Australia Southeast")
	ResourceLocationsEnum1BrazilSouth        = ResourceLocationsEnum1("Brazil South")
	ResourceLocationsEnum1CanadaCentral      = ResourceLocationsEnum1("Canada Central")
	ResourceLocationsEnum1CanadaEast         = ResourceLocationsEnum1("Canada East")
	ResourceLocationsEnum1CentralIndia       = ResourceLocationsEnum1("Central India")
	ResourceLocationsEnum1CentralUS          = ResourceLocationsEnum1("Central US")
	ResourceLocationsEnum1EastAsia           = ResourceLocationsEnum1("East Asia")
	ResourceLocationsEnum1EastUS             = ResourceLocationsEnum1("East US")
	ResourceLocationsEnum1EastUS2            = ResourceLocationsEnum1("East US 2")
	ResourceLocationsEnum1Global             = ResourceLocationsEnum1("global")
	ResourceLocationsEnum1JapanEast          = ResourceLocationsEnum1("Japan East")
	ResourceLocationsEnum1JapanWest          = ResourceLocationsEnum1("Japan West")
	ResourceLocationsEnum1KoreaCentral       = ResourceLocationsEnum1("Korea Central")
	ResourceLocationsEnum1KoreaSouth         = ResourceLocationsEnum1("Korea South")
	ResourceLocationsEnum1NorthCentralUS     = ResourceLocationsEnum1("North Central US")
	ResourceLocationsEnum1NorthEurope        = ResourceLocationsEnum1("North Europe")
	ResourceLocationsEnum1SouthCentralUS     = ResourceLocationsEnum1("South Central US")
	ResourceLocationsEnum1SouthIndia         = ResourceLocationsEnum1("South India")
	ResourceLocationsEnum1SoutheastAsia      = ResourceLocationsEnum1("Southeast Asia")
	ResourceLocationsEnum1UKSouth            = ResourceLocationsEnum1("UK South")
	ResourceLocationsEnum1UKWest             = ResourceLocationsEnum1("UK West")
	ResourceLocationsEnum1WestCentralUS      = ResourceLocationsEnum1("West Central US")
	ResourceLocationsEnum1WestEurope         = ResourceLocationsEnum1("West Europe")
	ResourceLocationsEnum1WestIndia          = ResourceLocationsEnum1("West India")
	ResourceLocationsEnum1WestUS             = ResourceLocationsEnum1("West US")
	ResourceLocationsEnum1WestUS2            = ResourceLocationsEnum1("West US 2")
)
