// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// Code generated by k8s-infra-gen. DO NOT EDIT.
package v20150101

// +kubebuilder:validation:Enum={"Parallel","Serial"}
type ResourceCopyMode string

const (
	ResourceCopyModeParallel = ResourceCopyMode("Parallel")
	ResourceCopyModeSerial   = ResourceCopyMode("Serial")
)
