// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// Code generated by k8s-infra-gen. DO NOT EDIT.
package v20150101

//Generated from: https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#/definitions/resourceCopy
type ResourceCopy struct {

	//BatchSize: The serial copy batch size
	BatchSize *int `json:"batchSize,omitempty"`

	//Count: Count of the copy
	Count *int `json:"count,omitempty"`

	//Mode: The copy mode
	Mode *ResourceCopyMode `json:"mode,omitempty"`

	//Name: Name of the copy
	Name *string `json:"name,omitempty"`
}
