// +build !ignore_autogenerated

/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v20150101

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceCopy) DeepCopyInto(out *ResourceCopy) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int)
		**out = **in
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(ResourceCopyMode)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceCopy.
func (in *ResourceCopy) DeepCopy() *ResourceCopy {
	if in == nil {
		return nil
	}
	out := new(ResourceCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLocations) DeepCopyInto(out *ResourceLocations) {
	*out = *in
	if in.Enum1 != nil {
		in, out := &in.Enum1, &out.Enum1
		*out = new(ResourceLocationsEnum1)
		**out = **in
	}
	if in.String0 != nil {
		in, out := &in.String0, &out.String0
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLocations.
func (in *ResourceLocations) DeepCopy() *ResourceLocations {
	if in == nil {
		return nil
	}
	out := new(ResourceLocations)
	in.DeepCopyInto(out)
	return out
}
