
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-microsoft-resources-infra-azure-com-v1-resourcegroup
  failurePolicy: Fail
  name: mresourcegroup.kb.io
  rules:
  - apiGroups:
    - microsoft.resources.infra.azure.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcegroups

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-microsoft-resources-infra-azure-com-v1-resourcegroup
  failurePolicy: Fail
  name: vresourcegroup.kb.io
  rules:
  - apiGroups:
    - microsoft.resources.infra.azure.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcegroups
