# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default

# TODO: We need to generate this?
resources:
# - bases/microsoft.resources.infra.azure.com_resourcegroups.yaml
- bases/microsoft.batch.infra.azure.com_batchaccounts.yaml
# +kubebuilder:scaffold:crdkustomizeresource

#patchesStrategicMerge:
#- patches/webhook_in_resourcegroups.yaml
#- patches/webhook_in_virtualnetworks.yaml
#- patches/webhook_in_routetables.yaml
#- patches/webhook_in_networksecuritygroups.yaml
#- patches/webhook_in_loadbalancers.yaml
#- patches/webhook_in_routes.yaml
#- patches/webhook_in_securityrules.yaml
#- patches/webhook_in_backendaddresspools.yaml
#- patches/webhook_in_loadbalancingrules.yaml
#- patches/webhook_in_outboundrules.yaml
#- patches/webhook_in_frontendipconfigurations.yaml
#- patches/webhook_in_inboundnatrules.yaml
#- patches/webhook_in_subnets.yaml
#- patches/webhook_in_virtualmachines.yaml
#- patches/webhook_in_virtualmachinescalesets.yaml
#- patches/webhook_in_networkinterfaces.yaml
## +kubebuilder:scaffold:crdkustomizewebhookpatch
#
#- patches/cainjection_in_resourcegroups.yaml
#- patches/cainjection_in_virtualnetworks.yaml
#- patches/cainjection_in_routetables.yaml
#- patches/cainjection_in_networksecuritygroups.yaml
#- patches/cainjection_in_loadbalancers.yaml
#- patches/cainjection_in_routes.yaml
#- patches/cainjection_in_securityrules.yaml
#- patches/cainjection_in_backendaddresspools.yaml
#- patches/cainjection_in_loadbalancingrules.yaml
#- patches/cainjection_in_outboundrules.yaml
#- patches/cainjection_in_frontendipconfigurations.yaml
#- patches/cainjection_in_inboundnatrules.yaml
#- patches/cainjection_in_resourcegroups.yaml
#- patches/cainjection_in_virtualnetworks.yaml
#- patches/cainjection_in_subnets.yaml
#- patches/cainjection_in_virtualmachines.yaml
#- patches/cainjection_in_virtualmachinescalesets.yaml
#- patches/cainjection_in_networkinterfaces.yaml
## +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
