# permissions for end users to view backendaddresspools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backendaddresspool-viewer-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - backendaddresspools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - backendaddresspools/status
  verbs:
  - get
