# permissions for end users to edit backendaddresspools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backendaddresspool-editor-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - backendaddresspools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - backendaddresspools/status
  verbs:
  - get
