# permissions for end users to view frontendipconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontendipconfiguration-viewer-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - frontendipconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - frontendipconfigurations/status
  verbs:
  - get
