# permissions for end users to edit frontendipconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontendipconfiguration-editor-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - frontendipconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - frontendipconfigurations/status
  verbs:
  - get
