# permissions for end users to view inboundnatrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inboundnatrule-viewer-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - inboundnatrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - inboundnatrules/status
  verbs:
  - get
