# permissions for end users to edit inboundnatrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inboundnatrule-editor-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - inboundnatrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - inboundnatrules/status
  verbs:
  - get
