# permissions for end users to view loadbalancingrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadbalancingrule-viewer-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - loadbalancingrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - loadbalancingrules/status
  verbs:
  - get
