# permissions for end users to edit loadbalancingrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadbalancingrule-editor-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - loadbalancingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - loadbalancingrules/status
  verbs:
  - get
