# permissions for end users to edit networkinterfaceipconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkinterfaceipconfiguration-editor-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - networkinterfaceipconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - networkinterfaceipconfigurations/status
  verbs:
  - get
