# permissions for end users to edit networksecuritygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networksecuritygroup-editor-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - networksecuritygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - networksecuritygroups/status
  verbs:
  - get
