# permissions for end users to view outboundrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: outboundrule-viewer-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - outboundrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - outboundrules/status
  verbs:
  - get
