# permissions to do viewer resourcegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcegroup-viewer-role
rules:
- apiGroups:
  - proto.infra.azure.com
  resources:
  - resourcegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proto.infra.azure.com
  resources:
  - resourcegroups/status
  verbs:
  - get
