
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - virtualnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - virtualnetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - microsoft.resources.infra.azure.com
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.resources.infra.azure.com
  resources:
  - resourcegroups/status
  verbs:
  - get
  - patch
  - update
