# permissions for end users to edit routetables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routetable-editor-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - routetables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - routetables/status
  verbs:
  - get
