# permissions for end users to view routetables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routetable-viewer-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - routetables
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - routetables/status
  verbs:
  - get
