# permissions for end users to view securityrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: securityrule-viewer-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - securityrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - securityrules/status
  verbs:
  - get
