# permissions for end users to edit securityrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: securityrule-editor-role
rules:
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - securityrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.network.infra.azure.com
  resources:
  - securityrules/status
  verbs:
  - get
