
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - microsoft.batch.infra.azure.com
  resources:
  - batchaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.batch.infra.azure.com
  resources:
  - batchaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - microsoft.documentdb.infra.azure.com
  resources:
  - databaseaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.documentdb.infra.azure.com
  resources:
  - databaseaccounts/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.resources.infra.azure.com
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.resources.infra.azure.com
  resources:
  - resourcegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - microsoft.storage.infra.azure.com
  resources:
  - storageaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.storage.infra.azure.com
  resources:
  - storageaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - microsoft.storage.infra.azure.com
  resources:
  - storageaccountsblobservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.storage.infra.azure.com
  resources:
  - storageaccountsblobservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - microsoft.storage.infra.azure.com
  resources:
  - storageaccountsblobservicesblobcontainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsoft.storage.infra.azure.com
  resources:
  - storageaccountsblobservicesblobcontainers/status
  verbs:
  - get
  - patch
  - update
