apiVersion: microsoft.network.infra.azure.com/v20191101
kind: VirtualNetwork
metadata:
  name: vnet-2019
spec:
  location: westus2
  resourceGroupRef:
    name: foo-2019
    namespace: default
  properties:
    addressSpace:
      addressPrefixes:
        - 10.0.0.0/16
    subnets:
      - name: subnet1
        properties:
          addressPrefix: 10.0.0.0/28
