apiVersion: microsoft.compute.infra.azure.com/v20191201
kind: VirtualMachineScaleSet
metadata:
  name: virtualmachinescaleset-sample
  namespace: default
spec:
  resourceGroupRef:
    name: resourcegroup-sample
    namespace: default
  location: westus2
  sku:
    name: Standard_D4_v3
    tier: Standard
    capacity: 2
  properties:
    upgradePolicy:
      mode: Manual
    virtualMachineProfile:
      storageProfile:
        osDisk:
          osType: Linux
          diskSizeGB: 30
          managedDisk:
            storageAccountType: Standard_LRS
          caching: ReadWrite
          createOption: FromImage
        imageReference:
          sku: 18.04-LTS
          publisher: Canonical
          version: latest
          offer: UbuntuServer
      osProfile:
        computerNamePrefix: k8s
        adminUsername: kadmin
        linuxConfiguration:
          ssh:
            publicKeys:
              - path: /home/kadmin/.ssh/authorized_keys
                keyData: "${SSH_PUB_KEY}"
      networkProfile:
        networkInterfaceConfigurations:
          - name: networkconfig1
            properties:
              primary: true
              enableIPForwarding: true
              ipConfigurations:
                - name: ipconfig1
                  properties:
                    subnetRef:
                      name: subnet-sample
                      namespace: default