apiVersion: microsoft.network.infra.azure.com/v20191101
kind: NetworkInterface
metadata:
  name: networkinterface-sample
  namespace: default
spec:
  location: westus2
  resourceGroupRef:
    name: resourcegroup-sample
    namespace: default
  properties:
    ipConfigurations:
      - name: networkinterfaceipconfiguration-1
        properties:
          subnetRef:
            name: subnet-sample
            namespace: default