apiVersion: microsoft.compute.infra.azure.com/v20191201
kind: VirtualMachine
metadata:
  name: virtualmachine-sample
  namespace: default
spec:
  resourceGroupRef:
    name: resourcegroup-sample
    namespace: default
  location: westus2
  properties:
    osProfile:
      adminUsername: kadmin
      computerName: k8sinfraVM
      linuxConfiguration:
        ssh:
          publicKeys:
            - path: /home/kadmin/.ssh/authorized_keys
              keyData: "${SSH_PUB_KEY}"
    hardwareProfile:
      vmSize: Standard_D4_v3
    storageProfile:
      osDisk:
        name: myOSDisk
        osType: Linux
        diskSizeGB: 30
        managedDisk:
          storageAccountType: Standard_LRS
        caching: ReadWrite
        createOption: FromImage
      imageReference:
        sku: 18.04-LTS
        publisher: Canonical
        version: latest
        offer: UbuntuServer
    networkProfile:
      networkInterfaceRefs:
        - name: networkinterface-sample
          namespace: default
          properties:
            primary: true
