// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// Code generated by k8s-infra-gen. DO NOT EDIT.
package v20200501

import (
	"fmt"
	"github.com/Azure/k8s-infra/hack/generated/apis/deploymenttemplate/v20150101"
	"github.com/Azure/k8s-infra/hack/generated/pkg/genruntime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
type NetworkSecurityGroups struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityGroups_Spec  `json:"spec,omitempty"`
	Status            NetworkSecurityGroup_Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type NetworkSecurityGroupsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityGroups `json:"items"`
}

type NetworkSecurityGroup_Status struct {
	AtProvider NetworkSecurityGroupsObservation `json:"atProvider"`
}

type NetworkSecurityGroups_Spec struct {
	ForProvider NetworkSecurityGroupsParameters `json:"forProvider"`
}

type NetworkSecurityGroupsObservation struct {

	//Etag: A unique read-only string that changes whenever the resource is updated.
	Etag *string `json:"etag,omitempty"`

	//Id: Resource ID.
	Id *string `json:"id,omitempty"`

	//Location: Resource location.
	Location *string `json:"location,omitempty"`

	//Name: Resource name.
	Name *string `json:"name,omitempty"`

	//Properties: Properties of the network security group.
	Properties *NetworkSecurityGroupPropertiesFormat_Status `json:"properties,omitempty"`

	//Tags: Resource tags.
	Tags map[string]string `json:"tags,omitempty"`

	//Type: Resource type.
	Type *string `json:"type,omitempty"`
}

type NetworkSecurityGroupsParameters struct {

	// +kubebuilder:validation:Required
	//ApiVersion: API Version of the resource type, optional when apiProfile is used
	//on the template
	ApiVersion NetworkSecurityGroupsSpecApiVersion `json:"apiVersion"`
	Comments   *string                             `json:"comments,omitempty"`

	//Condition: Condition of the resource
	Condition *bool                   `json:"condition,omitempty"`
	Copy      *v20150101.ResourceCopy `json:"copy,omitempty"`

	//DependsOn: Collection of resources this resource depends on
	DependsOn []string `json:"dependsOn,omitempty"`

	//Location: Location to deploy resource to
	Location string `json:"location,omitempty"`

	// +kubebuilder:validation:Required
	//Name: Name of the resource
	Name string `json:"name"`

	// +kubebuilder:validation:Required
	//Properties: Properties of the network security group.
	Properties NetworkSecurityGroupPropertiesFormat `json:"properties"`

	//Scope: Scope for the resource or deployment. Today, this works for two cases: 1)
	//setting the scope for extension resources 2) deploying resources to the tenant
	//scope in non-tenant scope deployments
	Scope *string `json:"scope,omitempty"`

	//Tags: Name-value pairs to add to the resource
	Tags map[string]string `json:"tags,omitempty"`

	// +kubebuilder:validation:Required
	//Type: Resource type
	Type NetworkSecurityGroupsSpecType `json:"type"`
}

//Generated from: https://schema.management.azure.com/schemas/2020-05-01/Microsoft.Network.json#/definitions/NetworkSecurityGroupPropertiesFormat
type NetworkSecurityGroupPropertiesFormat struct {

	//SecurityRules: A collection of security rules of the network security group.
	SecurityRules []SecurityRule `json:"securityRules,omitempty"`
}

//Generated from:
type NetworkSecurityGroupPropertiesFormat_Status struct {

	//DefaultSecurityRules: The default security rules of network security group.
	DefaultSecurityRules []SecurityRule_Status `json:"defaultSecurityRules,omitempty"`

	//FlowLogs: A collection of references to flow log resources.
	FlowLogs []FlowLog_Status `json:"flowLogs,omitempty"`

	//NetworkInterfaces: A collection of references to network interfaces.
	NetworkInterfaces []NetworkInterface_Status `json:"networkInterfaces,omitempty"`

	//ProvisioningState: The provisioning state of the network security group resource.
	ProvisioningState *ProvisioningState_Status `json:"provisioningState,omitempty"`

	//ResourceGuid: The resource GUID property of the network security group resource.
	ResourceGuid *string `json:"resourceGuid,omitempty"`

	//SecurityRules: A collection of security rules of the network security group.
	SecurityRules []SecurityRule_Status `json:"securityRules,omitempty"`

	//Subnets: A collection of references to subnets.
	Subnets []Subnet_Status `json:"subnets,omitempty"`
}

// +kubebuilder:validation:Enum={"2020-05-01"}
type NetworkSecurityGroupsSpecApiVersion string

const NetworkSecurityGroupsSpecApiVersion20200501 = NetworkSecurityGroupsSpecApiVersion("2020-05-01")

// +kubebuilder:validation:Enum={"Microsoft.Network/networkSecurityGroups"}
type NetworkSecurityGroupsSpecType string

const NetworkSecurityGroupsSpecTypeMicrosoftNetworkNetworkSecurityGroups = NetworkSecurityGroupsSpecType("Microsoft.Network/networkSecurityGroups")

//Generated from: https://schema.management.azure.com/schemas/2020-05-01/Microsoft.Network.json#/definitions/SecurityRule
type SecurityRule struct {

	//Name: The name of the resource that is unique within a resource group. This name
	//can be used to access the resource.
	Name *string `json:"name,omitempty"`

	//Properties: Properties of the security rule.
	Properties *SecurityRulePropertiesFormat `json:"properties,omitempty"`
}

func init() {
	SchemeBuilder.Register(&NetworkSecurityGroups{}, &NetworkSecurityGroupsList{})
}
