// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// Code generated by k8s-infra-gen. DO NOT EDIT.
package v20200501

import (
	"github.com/Azure/k8s-infra/hack/crossplane/apis/deploymenttemplate/v20150101"
	"github.com/crossplane/crossplane-runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
type NetworkSecurityGroupsSecurityRules struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSecurityGroupsSecurityRules_Spec `json:"spec,omitempty"`
	Status            SecurityRule_Status                     `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type NetworkSecurityGroupsSecurityRulesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkSecurityGroupsSecurityRules `json:"items"`
}

type NetworkSecurityGroupsSecurityRules_Spec struct {
	v1alpha1.ResourceSpec `json:",inline"`
	ForProvider           NetworkSecurityGroupsSecurityRulesParameters `json:"forProvider"`
}

type SecurityRule_Status struct {
	v1alpha1.ResourceStatus `json:",inline"`
	AtProvider              NetworkSecurityGroupsSecurityRulesObservation `json:"atProvider"`
}

type NetworkSecurityGroupsSecurityRulesObservation struct {

	//Etag: A unique read-only string that changes whenever the resource is updated.
	Etag *string `json:"etag,omitempty"`

	//Id: Resource ID.
	Id *string `json:"id,omitempty"`

	//Name: The name of the resource that is unique within a resource group. This name
	//can be used to access the resource.
	Name *string `json:"name,omitempty"`

	//Properties: Properties of the security rule.
	Properties *SecurityRulePropertiesFormat_Status `json:"properties,omitempty"`
}

type NetworkSecurityGroupsSecurityRulesParameters struct {

	// +kubebuilder:validation:Required
	//ApiVersion: API Version of the resource type, optional when apiProfile is used
	//on the template
	ApiVersion NetworkSecurityGroupsSecurityRulesSpecApiVersion `json:"apiVersion"`
	Comments   *string                                          `json:"comments,omitempty"`

	//Condition: Condition of the resource
	Condition *bool                   `json:"condition,omitempty"`
	Copy      *v20150101.ResourceCopy `json:"copy,omitempty"`

	//DependsOn: Collection of resources this resource depends on
	DependsOn []string `json:"dependsOn,omitempty"`

	//Location: Location to deploy resource to
	Location *v20150101.ResourceLocations `json:"location,omitempty"`

	// +kubebuilder:validation:Required
	//Name: Name of the resource
	Name string `json:"name"`

	// +kubebuilder:validation:Required
	//Properties: Properties of the security rule.
	Properties SecurityRulePropertiesFormat `json:"properties"`

	//Scope: Scope for the resource or deployment. Today, this works for two cases: 1)
	//setting the scope for extension resources 2) deploying resources to the tenant
	//scope in non-tenant scope deployments
	Scope *string `json:"scope,omitempty"`

	//Tags: Name-value pairs to add to the resource
	Tags map[string]string `json:"tags,omitempty"`

	// +kubebuilder:validation:Required
	//Type: Resource type
	Type NetworkSecurityGroupsSecurityRulesSpecType `json:"type"`
}

// +kubebuilder:validation:Enum={"2020-05-01"}
type NetworkSecurityGroupsSecurityRulesSpecApiVersion string

const NetworkSecurityGroupsSecurityRulesSpecApiVersion20200501 = NetworkSecurityGroupsSecurityRulesSpecApiVersion("2020-05-01")

// +kubebuilder:validation:Enum={"Microsoft.Network/networkSecurityGroups/securityRules"}
type NetworkSecurityGroupsSecurityRulesSpecType string

const NetworkSecurityGroupsSecurityRulesSpecTypeMicrosoftNetworkNetworkSecurityGroupsSecurityRules = NetworkSecurityGroupsSecurityRulesSpecType("Microsoft.Network/networkSecurityGroups/securityRules")

//Generated from: https://schema.management.azure.com/schemas/2020-05-01/Microsoft.Network.json#/definitions/SecurityRulePropertiesFormat
type SecurityRulePropertiesFormat struct {

	// +kubebuilder:validation:Required
	//Access: The network traffic is allowed or denied.
	Access SecurityRulePropertiesFormatAccess `json:"access"`

	//Description: A description for this rule. Restricted to 140 chars.
	Description *string `json:"description,omitempty"`

	//DestinationAddressPrefix: The destination address prefix. CIDR or destination IP
	//range. Asterisk '*' can also be used to match all source IPs. Default tags such
	//as 'VirtualNetwork', 'AzureLoadBalancer' and 'Internet' can also be used.
	DestinationAddressPrefix *string `json:"destinationAddressPrefix,omitempty"`

	//DestinationAddressPrefixes: The destination address prefixes. CIDR or
	//destination IP ranges.
	DestinationAddressPrefixes []string `json:"destinationAddressPrefixes,omitempty"`

	//DestinationApplicationSecurityGroups: The application security group specified
	//as destination.
	DestinationApplicationSecurityGroups []SubResource `json:"destinationApplicationSecurityGroups,omitempty"`

	//DestinationPortRange: The destination port or range. Integer or range between 0
	//and 65535. Asterisk '*' can also be used to match all ports.
	DestinationPortRange *string `json:"destinationPortRange,omitempty"`

	//DestinationPortRanges: The destination port ranges.
	DestinationPortRanges []string `json:"destinationPortRanges,omitempty"`

	// +kubebuilder:validation:Required
	//Direction: The direction of the rule. The direction specifies if rule will be
	//evaluated on incoming or outgoing traffic.
	Direction SecurityRulePropertiesFormatDirection `json:"direction"`

	// +kubebuilder:validation:Required
	//Priority: The priority of the rule. The value can be between 100 and 4096. The
	//priority number must be unique for each rule in the collection. The lower the
	//priority number, the higher the priority of the rule.
	Priority int `json:"priority"`

	// +kubebuilder:validation:Required
	//Protocol: Network protocol this rule applies to.
	Protocol SecurityRulePropertiesFormatProtocol `json:"protocol"`

	//SourceAddressPrefix: The CIDR or source IP range. Asterisk '*' can also be used
	//to match all source IPs. Default tags such as 'VirtualNetwork',
	//'AzureLoadBalancer' and 'Internet' can also be used. If this is an ingress rule,
	//specifies where network traffic originates from.
	SourceAddressPrefix *string `json:"sourceAddressPrefix,omitempty"`

	//SourceAddressPrefixes: The CIDR or source IP ranges.
	SourceAddressPrefixes []string `json:"sourceAddressPrefixes,omitempty"`

	//SourceApplicationSecurityGroups: The application security group specified as
	//source.
	SourceApplicationSecurityGroups []SubResource `json:"sourceApplicationSecurityGroups,omitempty"`

	//SourcePortRange: The source port or range. Integer or range between 0 and 65535.
	//Asterisk '*' can also be used to match all ports.
	SourcePortRange *string `json:"sourcePortRange,omitempty"`

	//SourcePortRanges: The source port ranges.
	SourcePortRanges []string `json:"sourcePortRanges,omitempty"`
}

//Generated from:
type SecurityRulePropertiesFormat_Status struct {

	// +kubebuilder:validation:Required
	//Access: The network traffic is allowed or denied.
	Access SecurityRuleAccess_Status `json:"access"`

	//Description: A description for this rule. Restricted to 140 chars.
	Description *string `json:"description,omitempty"`

	//DestinationAddressPrefix: The destination address prefix. CIDR or destination IP
	//range. Asterisk '*' can also be used to match all source IPs. Default tags such
	//as 'VirtualNetwork', 'AzureLoadBalancer' and 'Internet' can also be used.
	DestinationAddressPrefix *string `json:"destinationAddressPrefix,omitempty"`

	//DestinationAddressPrefixes: The destination address prefixes. CIDR or
	//destination IP ranges.
	DestinationAddressPrefixes []string `json:"destinationAddressPrefixes,omitempty"`

	//DestinationApplicationSecurityGroups: The application security group specified
	//as destination.
	DestinationApplicationSecurityGroups []ApplicationSecurityGroup_Status `json:"destinationApplicationSecurityGroups,omitempty"`

	//DestinationPortRange: The destination port or range. Integer or range between 0
	//and 65535. Asterisk '*' can also be used to match all ports.
	DestinationPortRange *string `json:"destinationPortRange,omitempty"`

	//DestinationPortRanges: The destination port ranges.
	DestinationPortRanges []string `json:"destinationPortRanges,omitempty"`

	// +kubebuilder:validation:Required
	//Direction: The direction of the rule. The direction specifies if rule will be
	//evaluated on incoming or outgoing traffic.
	Direction SecurityRuleDirection_Status `json:"direction"`

	//Priority: The priority of the rule. The value can be between 100 and 4096. The
	//priority number must be unique for each rule in the collection. The lower the
	//priority number, the higher the priority of the rule.
	Priority *int `json:"priority,omitempty"`

	// +kubebuilder:validation:Required
	//Protocol: Network protocol this rule applies to.
	Protocol SecurityRulePropertiesFormatStatusProtocol `json:"protocol"`

	//ProvisioningState: The provisioning state of the security rule resource.
	ProvisioningState *ProvisioningState_Status `json:"provisioningState,omitempty"`

	//SourceAddressPrefix: The CIDR or source IP range. Asterisk '*' can also be used
	//to match all source IPs. Default tags such as 'VirtualNetwork',
	//'AzureLoadBalancer' and 'Internet' can also be used. If this is an ingress rule,
	//specifies where network traffic originates from.
	SourceAddressPrefix *string `json:"sourceAddressPrefix,omitempty"`

	//SourceAddressPrefixes: The CIDR or source IP ranges.
	SourceAddressPrefixes []string `json:"sourceAddressPrefixes,omitempty"`

	//SourceApplicationSecurityGroups: The application security group specified as
	//source.
	SourceApplicationSecurityGroups []ApplicationSecurityGroup_Status `json:"sourceApplicationSecurityGroups,omitempty"`

	//SourcePortRange: The source port or range. Integer or range between 0 and 65535.
	//Asterisk '*' can also be used to match all ports.
	SourcePortRange *string `json:"sourcePortRange,omitempty"`

	//SourcePortRanges: The source port ranges.
	SourcePortRanges []string `json:"sourcePortRanges,omitempty"`
}

//Generated from:
// +kubebuilder:validation:Enum={"Allow","Deny"}
type SecurityRuleAccess_Status string

const (
	SecurityRuleAccess_StatusAllow = SecurityRuleAccess_Status("Allow")
	SecurityRuleAccess_StatusDeny  = SecurityRuleAccess_Status("Deny")
)

//Generated from:
// +kubebuilder:validation:Enum={"Inbound","Outbound"}
type SecurityRuleDirection_Status string

const (
	SecurityRuleDirection_StatusInbound  = SecurityRuleDirection_Status("Inbound")
	SecurityRuleDirection_StatusOutbound = SecurityRuleDirection_Status("Outbound")
)

// +kubebuilder:validation:Enum={"Allow","Deny"}
type SecurityRulePropertiesFormatAccess string

const (
	SecurityRulePropertiesFormatAccessAllow = SecurityRulePropertiesFormatAccess("Allow")
	SecurityRulePropertiesFormatAccessDeny  = SecurityRulePropertiesFormatAccess("Deny")
)

// +kubebuilder:validation:Enum={"Inbound","Outbound"}
type SecurityRulePropertiesFormatDirection string

const (
	SecurityRulePropertiesFormatDirectionInbound  = SecurityRulePropertiesFormatDirection("Inbound")
	SecurityRulePropertiesFormatDirectionOutbound = SecurityRulePropertiesFormatDirection("Outbound")
)

// +kubebuilder:validation:Enum={"Ah","Esp","Icmp","*","Tcp","Udp"}
type SecurityRulePropertiesFormatProtocol string

const (
	SecurityRulePropertiesFormatProtocolAh   = SecurityRulePropertiesFormatProtocol("Ah")
	SecurityRulePropertiesFormatProtocolEsp  = SecurityRulePropertiesFormatProtocol("Esp")
	SecurityRulePropertiesFormatProtocolIcmp = SecurityRulePropertiesFormatProtocol("Icmp")
	SecurityRulePropertiesFormatProtocolStar = SecurityRulePropertiesFormatProtocol("*")
	SecurityRulePropertiesFormatProtocolTcp  = SecurityRulePropertiesFormatProtocol("Tcp")
	SecurityRulePropertiesFormatProtocolUdp  = SecurityRulePropertiesFormatProtocol("Udp")
)

// +kubebuilder:validation:Enum={"Ah","Esp","Icmp","*","Tcp","Udp"}
type SecurityRulePropertiesFormatStatusProtocol string

const (
	SecurityRulePropertiesFormatStatusProtocolAh   = SecurityRulePropertiesFormatStatusProtocol("Ah")
	SecurityRulePropertiesFormatStatusProtocolEsp  = SecurityRulePropertiesFormatStatusProtocol("Esp")
	SecurityRulePropertiesFormatStatusProtocolIcmp = SecurityRulePropertiesFormatStatusProtocol("Icmp")
	SecurityRulePropertiesFormatStatusProtocolStar = SecurityRulePropertiesFormatStatusProtocol("*")
	SecurityRulePropertiesFormatStatusProtocolTcp  = SecurityRulePropertiesFormatStatusProtocol("Tcp")
	SecurityRulePropertiesFormatStatusProtocolUdp  = SecurityRulePropertiesFormatStatusProtocol("Udp")
)

func init() {
	SchemeBuilder.Register(&NetworkSecurityGroupsSecurityRules{}, &NetworkSecurityGroupsSecurityRulesList{})
}
