// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
// Code generated by k8s-infra-gen. DO NOT EDIT.
package v20200501

import (
	"fmt"
	"github.com/Azure/k8s-infra/hack/generated/apis/deploymenttemplate/v20150101"
	"github.com/Azure/k8s-infra/hack/generated/pkg/genruntime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
type NetworkWatchers struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkWatchers_Spec  `json:"spec,omitempty"`
	Status            NetworkWatcher_Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type NetworkWatchersList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkWatchers `json:"items"`
}

//Generated from:
type NetworkWatcher_Status struct {

	//Etag: A unique read-only string that changes whenever the resource is updated.
	Etag *string `json:"etag,omitempty"`

	//Id: Resource ID.
	Id *string `json:"id,omitempty"`

	//Location: Resource location.
	Location *string `json:"location,omitempty"`

	//Name: Resource name.
	Name *string `json:"name,omitempty"`

	//Properties: Properties of the network watcher.
	Properties *NetworkWatcherPropertiesFormat_Status `json:"properties,omitempty"`

	//Tags: Resource tags.
	Tags map[string]string `json:"tags,omitempty"`

	//Type: Resource type.
	Type *string `json:"type,omitempty"`
}

type NetworkWatchers_Spec struct {
	ForProvider NetworkWatchersParameters `json:"forProvider"`
}

//Generated from:
type NetworkWatcherPropertiesFormat_Status struct {

	//ProvisioningState: The provisioning state of the network watcher resource.
	ProvisioningState *ProvisioningState_Status `json:"provisioningState,omitempty"`
}

type NetworkWatchersParameters struct {

	// +kubebuilder:validation:Required
	//ApiVersion: API Version of the resource type, optional when apiProfile is used
	//on the template
	ApiVersion NetworkWatchersSpecApiVersion `json:"apiVersion"`
	Comments   *string                       `json:"comments,omitempty"`

	//Condition: Condition of the resource
	Condition *bool                   `json:"condition,omitempty"`
	Copy      *v20150101.ResourceCopy `json:"copy,omitempty"`

	//DependsOn: Collection of resources this resource depends on
	DependsOn []string `json:"dependsOn,omitempty"`

	//Location: Location to deploy resource to
	Location string `json:"location,omitempty"`

	// +kubebuilder:validation:Required
	//Name: Name of the resource
	Name string `json:"name"`

	// +kubebuilder:validation:Required
	//Properties: Properties of the network watcher.
	Properties interface{} `json:"properties"`

	//Scope: Scope for the resource or deployment. Today, this works for two cases: 1)
	//setting the scope for extension resources 2) deploying resources to the tenant
	//scope in non-tenant scope deployments
	Scope *string `json:"scope,omitempty"`

	//Tags: Name-value pairs to add to the resource
	Tags map[string]string `json:"tags,omitempty"`

	// +kubebuilder:validation:Required
	//Type: Resource type
	Type NetworkWatchersSpecType `json:"type"`
}

// +kubebuilder:validation:Enum={"2020-05-01"}
type NetworkWatchersSpecApiVersion string

const NetworkWatchersSpecApiVersion20200501 = NetworkWatchersSpecApiVersion("2020-05-01")

// +kubebuilder:validation:Enum={"Microsoft.Network/networkWatchers"}
type NetworkWatchersSpecType string

const NetworkWatchersSpecTypeMicrosoftNetworkNetworkWatchers = NetworkWatchersSpecType("Microsoft.Network/networkWatchers")

func init() {
	SchemeBuilder.Register(&NetworkWatchers{}, &NetworkWatchersList{})
}
