name: ci
on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup KinD
        uses: engineerd/setup-kind@v0.2.0
      - name: Make test
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: make test-cover
      - name: Build docker image
        run: make docker-build
#      - name: Convert coverage to lcov
#        uses: jandelgado/gcov2lcov-action@v1.0.0
#        with:
#          infile: profile.cov
#          outfile: coverage.lcov
#      - name: Coveralls
#        uses: coverallsapp/github-action@v1.0.1
#        with:
#          github-token: ${{ secrets.github_token }}
#          path-to-lcov: coverage.lcov